version: '3'

services:
    postgres:
        image: postgres:16
        container_name: nest_postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: nest_db
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
    loki:
        image: grafana/loki:2.9.0
        ports:
            - '3100:3100'
        command: -config.file=/etc/loki/local-config.yml
        volumes:
            - ./loki-config.yml:/etc/loki/local-config.yml
    grafana:
        image: grafana/grafana:latest
        ports:
            - '3000:3000'
        environment:
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
        volumes:
            - grafana-storage:/var/lib/grafana

volumes:
    grafana-storage:
    postgres_data:
        driver: local
