import type { Metadata } from "next";
import "../assets/styles/globals.css";
import { ThemeProvider } from "@/themes/ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased w-full bg-foreground dark:bg-background text-black dark:text-white`}
      >
        <ThemeProvider>
          <section className="flex h-screen flex-col ">
            <main className="flex-1"> {children}</main>
          </section>
        </ThemeProvider>
      </body>
    </html>
  );
}
